{{- if .Values.enableCertManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "scheduler-plugins-as-a-second-scheduler.fullname" . }}-serving-cert
  labels:
  {{- include "scheduler-plugins-as-a-second-scheduler.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "scheduler-plugins-as-a-second-scheduler.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ include "scheduler-plugins-as-a-second-scheduler.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{
    .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "scheduler-plugins-as-a-second-scheduler.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert
{{- end}}
