apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "scheduler-plugins-as-a-second-scheduler.name" . }}-mutating-webhook-configuration
  {{- if .Values.enableCertManager }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "scheduler-plugins-as-a-second-scheduler.fullname" . }}-serving-cert
  {{- end}}
  labels:
  {{- include "scheduler-plugins-as-a-second-scheduler.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "scheduler-plugins-as-a-second-scheduler.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-v1-fluence
      {{- with (index .Values.webhookService.ports 0) }}
      port: {{ .port }}
      {{- end }}

  failurePolicy: Fail
  name: morascache.kb.io
  rules:
  - apiGroups:
    - ""
    - core
    - apps
    - batch
    - scheduling.x-k8s.io
    apiVersions:
    - v1
    - v1alpha1
    operations:
    - CREATE
    resources:
    - pods
    - jobs
    - statefulsets
    - deployments
    - replicasets

# Can uncomment this if we want to mutate the pod groups after creation
#    - podgroups
  sideEffects: None
