apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "scheduler-plugins-as-a-second-scheduler.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "scheduler-plugins-as-a-second-scheduler.labels" . | nindent 4 }}
spec:
  selfSigned: {}
