apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduler-plugins-as-a-second-scheduler.fullname" . }}-webhook-service
  labels:
    app.kubernetes.io/component: webhook
#    app.kubernetes.io/created-by: oras-operator
#    app.kubernetes.io/part-of: oras-operator
  {{- include "scheduler-plugins-as-a-second-scheduler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
  {{- include "scheduler-plugins-as-a-second-scheduler.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}
