apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: lammps
spec:
  scheduleTimeoutSeconds: 500
  minMember: 27
---
apiVersion: kubeflow.org/v2beta1
kind: MPIJob 
metadata:          
  name: lammps
spec:                 
  slotsPerWorker: 1
  runPolicy:                       
    cleanPodPolicy: Running                            
    #    ttlSecondsAfterFinished: 60
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:                                      
    Launcher:                       
      replicas: 1         
      template:           
        spec:                                 
          containers:
          - image: quay.io/cmisale1/lammps:ocp
            imagePullPolicy: Always
            name: mpi-launcher
            env:
#            - name: OMP_NUM_THREADS
#              value: "2"
#            - name: LD_PRELOAD
#              value: "libgomp.so.1"
            command:
            - bash
            - -cx 
            - ". /etc/profile && mpirun --mca orte_launch_agent /opt/view/bin/orted --mca plm_rsh_agent rsh -x PATH -x LD_LIBRARY_PATH -n 34 --oversubscribe --map-by socket lmp -v x 27 -v y 1 -v z 1 -in in.reaxc.hns -nocite"
            resources:
              limits:
                cpu: 1
                memory: 2Gi
          tolerations:
          - key: "launcher"
            operator: "Exists"
            effect: "NoSchedule"
    Worker:
      replicas: 27
      template:
        metadata:
            app: lammps
            labels:
              app: lammps
              pod-group.scheduling.sigs.k8s.io: lammps
        spec:
          schedulerName: fluence
          containers:
          - image: quay.io/cmisale1/lammps:ocp
            imagePullPolicy: Always
            name: worker
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config   
            resources:
              limits:
                cpu: 2
                memory: 2Gi
              requests:
                cpu: 2
                memory: 2Gi
